name: Lint

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Setup Python 3.14
      uses: actions/setup-python@v6
      with:
          python-version: "3.14"

    - name: Setup R
      id: setup-r
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.5.3"
        use-public-rspm: true

    - name: Cache pre-commit environments
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pre-commit
          ~/.local/share/renv/cache
        key: pre-commit-v1-${{ env.pythonLocation }}-${{ steps.setup-r.outputs.installed-r-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-v1-${{ env.pythonLocation }}-${{ steps.setup-r.outputs.installed-r-version }}-

    - name: Install pre-commit
      run: python -m pip install pre-commit

    - name: Run pre-commit hooks
      run: pre-commit run --all-files
